# Copyright 2018-2021 Crown Copyright
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deployment-jvm.name" . }}-configmap
  namespace: {{ include "palisade.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "deployment-jvm.name" . }}
    helm.sh/chart: {{ include "deployment-jvm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  application-akka.yaml: |
    akka:
      discovery.config.services.kafka.endpoints:
      - host: kafka.palisade-shared.svc.cluster.local
        port: 9092
  application-redis.yaml: |
    spring:
      {{- if .Values.global.topicPrefix }}
      data:
        redis:
          repositories:
            key-prefix: {{ printf "%s:" .Values.global.topicPrefix | quote }}
      {{ end }}
      redis:
        host: redis-master.palisade-shared.svc.cluster.local
        port: 6379
