default:
  type: uk.gov.gchq.syntheticdatagenerator.types.Employee
  format: avro

# Locally, we use the SimpleResourceService which does a Files.walk(...) so no need to prepopulate
# Used by the Resource Service to infer the types of the (many thousands of) resources created for the performance test
resource:
  defaultType: ${default.type}